package HelloNaming;


/**
* HelloNaming/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldName.idl
* 09 March 2017 18:38:01 o'clock GMT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
