package Test;


/**
* Test/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldName.idl
* 10 March 2017 05:51:10 o'clock GMT
*/

public interface HelloOperations 
{
  int addNumbers (int a, int b, int c, int d);
} // interface HelloOperations
