package Test;


/**
* Test/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldName.idl
* 10 March 2017 04:09:13 o'clock GMT
*/

public interface HelloOperations
{
  String addNumbers ();
} // interface HelloOperations
