package Test;


/**
* Test/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldName.idl
* 10 March 2017 04:09:13 o'clock GMT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
